/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import java.awt.Color;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class View extends javax.swing.JFrame {

    static JButton jb[] = new JButton[40];
    static JLabel jt[] = new JLabel[40];
    JPanel jp[] = new JPanel[40];
    Function b = new Function();
    int k = 0, l = 0;
    String ip[] = new String[40];
    static String defaultgateway;
    static ImageIcon on = new ImageIcon("on.png");
    ResultSet rs = null;
    //String ipboardcast = "192.168.14.255";
    String ipboardcast ="127.0.0.255";
    
    ImageIcon student = new ImageIcon("student.png");
    ImageIcon course = new ImageIcon("course.png");
    ImageIcon ban = new ImageIcon("ban.png");
    ImageIcon IP = new ImageIcon("ip.png");
    ImageIcon criminal = new ImageIcon("criminal.png");
    ImageIcon block = new ImageIcon("block.png");
    

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        
        addstudent.setIcon(student);
        addstudent.setHorizontalTextPosition(AbstractButton.CENTER);
        addstudent.setVerticalTextPosition(AbstractButton.BOTTOM);
                
        banlist.setIcon(ban);
        banlist.setHorizontalTextPosition(AbstractButton.CENTER);
        banlist.setVerticalTextPosition(AbstractButton.BOTTOM);
        
        jButton3.setIcon(IP);
        jButton3.setHorizontalTextPosition(AbstractButton.CENTER);
        jButton3.setVerticalTextPosition(AbstractButton.BOTTOM);
        
        jButton1.setIcon(criminal);
        jButton1.setHorizontalTextPosition(AbstractButton.CENTER);
        jButton1.setVerticalTextPosition(AbstractButton.BOTTOM);
        
        Blockinternet.setIcon(block);
        Blockinternet.setHorizontalTextPosition(AbstractButton.CENTER);
        Blockinternet.setVerticalTextPosition(AbstractButton.BOTTOM);
        IPList();
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 8; j++) {
                jb[k] = new JButton();
                jt[k] = new JLabel(ip[k]);
                jp[k] = new JPanel();
                jp[k].setBackground(Color.yellow);
                jp[k].add(jb[k]);
                jp[k].add(jt[k]);
                jPanel1.add(jp[k]);
                k++;
            }
        }

    }

    private void IPList() {
        Connection connection = getconnect();
        String sql = " SELECT * FROM  ip";
        PreparedStatement pre;
        int i = 0;
        try {
            pre = connection.prepareStatement(sql);
            rs = pre.executeQuery();
            while (rs.next()) {
                ip[i] = rs.getString("IP_Address");
                i++;
            }
        } catch (SQLException ex) {
        }finally {
            try {
                if (connection != null) {
                    System.out.println("close");
                    rs.close();
                    connection.close();
                }
            } catch (SQLException se) {
            }
        }
    }

    public Connection getconnect() {
        Connection con;
        String url = "jdbc:mysql://localhost/controllab";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, "root", "");
            return con;
        } catch (ClassNotFoundException | SQLException ex) {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addstudent = new javax.swing.JButton();
        banlist = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Blockinternet = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 51, 102));
        jPanel1.setLayout(new java.awt.GridLayout(5, 8, 2, 1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        addstudent.setText("Edit student");
        addstudent.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addstudent.setPreferredSize(new java.awt.Dimension(110, 75));
        addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentActionPerformed(evt);
            }
        });

        banlist.setText("Ban list");
        banlist.setPreferredSize(new java.awt.Dimension(110, 75));
        banlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banlistActionPerformed(evt);
            }
        });

        jButton3.setText("Edit IP");
        jButton3.setPreferredSize(new java.awt.Dimension(110, 75));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Blockinternet.setText("Block Internet");
        Blockinternet.setPreferredSize(new java.awt.Dimension(110, 75));
        Blockinternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockinternetActionPerformed(evt);
            }
        });

        jButton1.setText("Criminal");
        jButton1.setPreferredSize(new java.awt.Dimension(110, 75));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Blockinternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addstudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(banlist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(addstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(banlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Blockinternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentActionPerformed
        b.editstudent();
    }//GEN-LAST:event_addstudentActionPerformed

    private void banlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banlistActionPerformed
        b.banlist();
    }//GEN-LAST:event_banlistActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        EditIP eip = new EditIP();
        eip.main();
        validate();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void BlockinternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockinternetActionPerformed
        String gateway;
        DatagramPacket p;
        InetAddress a;
        DatagramSocket s;
        try {
            a = InetAddress.getByName(ipboardcast);
            s = new DatagramSocket();
            if (Blockinternet.isSelected()) {
                gateway = "blockinternet#";
            } else {
                gateway = "unblockinternet#";
            }
            p = new DatagramPacket(gateway.getBytes(), gateway.getBytes().length, a, 8888);
            s.send(p);
            s.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_BlockinternetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        b.checkoffen();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String[] args) {
        Login a = new Login();
        View v = new View();
        a.setModal(true);
        a.setVisible(true);
        if (a.confirm) {
            v.setVisible(true);
            Connect connect = new Connect();
            connect.createserver();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Blockinternet;
    private javax.swing.JButton addstudent;
    private javax.swing.JButton banlist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
